w3c/wot-usecases

- USE-CASES/oauth.md
As the title says this PR adds protocol diagrams for each flow. Currently, I only added `code`, `device`, and `client` diagrams. I am planning to add the rest very soon. I also made some minor improvements and pointed to a nice IETF draft about OAuth 2.0 over CoAP. I suggest checking it out before the next call. In particular, I think that [section 5.2](https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-35#section-5.2) can be useful for our discussion.
> [OAuth 2.0] add flow diagrams and improve flow description

- CONTRIBUTIONS/README.md
- CONTRIBUTIONS/include.pl
- CONTRIBUTIONS/md2html.sh
I provided a Perl script to convert MD files into HTML files (=HTML fragments to be strict).
Now I'd like to provide another tool to include all the auto-generated HTML fragments into the main index.html file of the [WoT Use Cases and Requirements](https://w3c.github.io/wot-usecases/).
Note that you need to put `#include "your-expected.html"` on the line where you want to include the HTML fragment. Please see also the updated README.md within this PR for the detailed usage of the tools.
> add inclusion tool and how to use it (and the previous tool)

- CONTRIBUTIONS/md2html.pl
Sorry but I've just remembered (1) we use ReSpec for spec generation and (2) ReSpec requires us some specific notation for section and heading, i.e., &lt;h2&gt; surrounded by &lt;section&gt; and &lt/section&gt;.
Note that we can use &lt;h3&gt;, &lt;h4&gt;, etc. instead of &lt;h2&gt; for human readability if we want.
Please see also the [Respec Editor's Guide](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#user-content-sections).
> fix md2html.pl for respec

- CONTRIBUTIONS/md2html.pl
- index.html
The updated [index.html](https://w3c.github.io/wot-usecases/#use-cases) includes all the proposed use cases at the [USE-CASES area](https://github.com/w3c/wot-usecases/tree/master/USE-CASES). However, the format is actually not well-readable because I used &lt;h3&gt;, &lt;h4&gt;, etc. (sorry)
Therefore I modified the [md2html.pl](https://github.com/w3c/wot-usecases/blob/master/CONTRIBUTIONS/md2html.pl) to use &lt;h2&gt; for headings and &lt;dl&gt; for the labels of each use case description.
I believe this modification significantly improves the readability for further edits.
Please see also the preview below.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/36.html" title="Last updated on Aug 6, 2020, 7:49 AM UTC (acabe0b)">Preview</a> | <a …
> modify md2html to use dl

- index.html
I rewote the reference section to fix tre respec format and moved the head section. And I commented out the reference section.
But there were not enough the information of each references. So  I added the information that I was able to look up. But It was not enough. I think we should check them.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/72.html" title="Last updated on Dec 8, 2020, 12:00 PM UTC (08c1c44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/72/4def1c6...08c1c44.html" title="Last updated on Dec 8, 2020, 12:00 PM UTC (08c1c44)">Diff</a>
> move reference section into head section

- index.html
I added reference link about Hybridcast.
- [IPTVFJ STD-0013 "Hybridcast Operational Guideline Version 2.8" (application forms)](http://www.iptvforum.jp/download/input.html)
- [Reference Implementations (our github repositories)](https://github.com/nhkrd)
Could you please confirm it.
***
<a href="https://pr-preview.s3.amazonaws.com/abes-jg/wot-usecases/pull/73.html" title="Last updated on Dec 16, 2020, 12:33 AM UTC (b7e6580)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/73/be363fc...abes-jg:b7e6580.html" title="Last updated on Dec 16, 2020, 12:33 AM UTC (b7e6580)">Diff</a>
> Hybridcast Reference Infromation

- index.html
Christine Perey and I met and wanted to review the AR/VR Guide use case to capture better its relationship to WoT, e.g. displaying data from WoT devices and sensors.   These points were discussed previously via email with the original submitted.  
This PR should be discussed with the original submitter before being merged as some significant changes have been made.  In particular, the original description had many options in the original descriptions (AR or VR, headset or handheld display, etc) which made the description confusing and the requirements less clear. So we refocused the description on the "AR with a headset" use case which is the one that surfaces real-world geolocation information as well as some specific security concerns (which I have also added).  The other possibilities …
> Focus AR/VR Guide use case on AR

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/130.html" title="Last updated on May 4, 2021, 1:12 PM UTC (8b51826)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/130/5a30db5...8b51826.html" title="Last updated on May 4, 2021, 1:12 PM UTC (8b51826)">Diff</a>
> use short name wot-usecases, remove company names in section 2.3.3

- USE-CASES/portable-building-applications.md
Addresses the request in https://github.com/w3c/wot-usecases/issues/121
Happy to take comments, suggestions, questions and critiques!
> Add portable building apps use case draft

- index.html
* the aspect ratio of the NHK's diagram (scenario_nhk.png) was broken
* added "height: auto;" to the CSS setting for "resize" class
* the width of the ECHONET diagram (wot-use-case-echoet.png) was too wide
* added <div class="resize"> to apply the (fixed version of) CSS setting above to make the width of the diagram 100% of the document
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/146.html" title="Last updated on Sep 27, 2021, 7:16 PM UTC (92149e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/146/4294f06...92149e7.html" title="Last updated on Sep 27, 2021, 7:16 PM UTC (92149e7)">Diff</a>
> fix resize CSS

- index.html
Description of EdgeX and WoT's relationship to it.  Note that this should be carefully reviewed for accuracy, we don't want to misrepresent a potential partner's project.  In particular, we need to check if they have adopted another mechanism for formally expressing metadata (e.g. OpenAPI) since I last looked at it in detail.
Also, EdgeX is basically an example of a software stack for a "hub" architecture.  There are several other examples of such architectures, including WebThings, SmartThings, Hubicity, etc.  So I have listed some related issues in architecture (see below) that relate to this.  Also, it seems to me that if we are going to talk about EdgeX we probably want to also talk about WebThings and maybe mention some of the other ones (there is a list in the issues of the …
> EdgeX Liaison Section

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/169.html" title="Last updated on Dec 14, 2021, 1:42 PM UTC (7fc29b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/169/5529421...7fc29b6.html" title="Last updated on Dec 14, 2021, 1:42 PM UTC (7fc29b6)">Diff</a>
> commenting liaison sections without contents

- index.html
- Add (small modification of) agreed-upon sentence for health privacy section saying that relevant privacy standards should be followed
- Add citations of HIPPA, GDPR, and PIPEDA
- Add local references for each of HIPAA, GDPR, and PIPEDA (not in SpecRef database)
Resolves https://github.com/w3c/wot-usecases/issues/50
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/175.html" title="Last updated on Jan 25, 2022, 3:19 PM UTC (0c3ed48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/175/e58da67...0c3ed48.html" title="Last updated on Jan 25, 2022, 3:19 PM UTC (0c3ed48)">Diff</a>
> Update Health Privacy Section

- REQUIREMENTS/requirements-template.md
As agreed on the UC call of 07.02, we remove this section since there is no consensus to where to put this information about justification.
> Remove Business Impact from Requirements Template

- .github/ISSUE_TEMPLATE/WoT-UseCases-Template.yml
Based on the discussion results of ["What to be done?" is ambiguous #287](https://github.com/w3c/wot-usecases/issues/287), I change the order of item of WoT-UseCases-Template.yml.
Summary
Why WoT
Gaps
Description
I created PR [Change the order of items of sample-usecase-template.yml based Issue … #293](https://github.com/w3c/wot-usecases/pull/293). But this file was removed. This PR was closed. Then I create new PR. See also [Delete old issue templates #294](https://github.com/w3c/wot-usecases/pull/294)
> Change the order of items of WoT-UseCases-Template.yml

- .github/ISSUE_TEMPLATE/use-case-template.yml
After talking with @chachamimm , I would like to provide a new use case template based on my experience in writing #296 and my expectations as a spec editor. This one specifically focuses on identifying gaps, which is my interest as a spec editor. 
This can seem a bit radical since it does not contain a lot of the fields present in the other use case templates we have seen so far. 
My main goal in this new template is addressing the following:
A use case submission should come from someone with the question of “I want to make sure that {my use case} is possible with WoT. However, due to lack of {gap}, I am not able to solve this in a standardized way.”
Since we need to assess the use case, we need more information:
- Some information about the background of the use case, such as some …
> New Use Case Template Proposal

- index.html
In the context of the OAuth 2.0 use case, I noticed some (outdated) text regarding ACE-OAuth, an OAuth-based authentication and authorization framework for constrained environments. This PR updates the references and the text itself, turning the "comment" into a short paragraph pointing to the RFCs that have been published in the meantime.
I am not sure if this is already good enough, though, or whether this section should rather be removed and maybe even turned into its own use-case – let me know if you have any thoughts here :)
CC @mmccool @relu91
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-usecases/pull/248.html" title="Last updated on Nov 27, 2023, 11:52 PM UTC (b657397)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/248/d7ce713...JKRhb:b657 …
> Update OAuth 2.0 section on ACE-OAuth

- .github/ISSUE_TEMPLATE/use-case-template.yml
Editing the use case template, I've noticed two small typos. This PR proposes a fix.
> Fix typos in use case template

- .github/ISSUE_TEMPLATE/use-case-template.yml
Filling out the use case template, I got the impression that the way the specifications are currently listed in the text areas (as bullet points) is not really ideal and partially inconsistent. This PR suggests changing the template to ask the user to provide their input under subsections instead, making the content easier to navigate after submission.
> Turn bullet points in use case template into subsections

- .github/ISSUE_TEMPLATE/user-story-template.yaml
Filling out the user story template, I noticed that some of the fields currently end up being rendered as Markdown code blocks, which is probably not intended (see https://github.com/JKRhb/wot-usecases/issues/1). This PR slightly adjusts the template, removing the lines in the template that cause this behavior.
> fix: don't render user story fields as Markdown code blocks

- CONTRIBUTIONS/md2html_YAML.pl
Based on [Issue #326](https://github.com/w3c/wot-usecases/issues/326), I have made changes to the perl script from md2html.pl for automatic conversion from US/UC/UCC MD to HTML.
> perl script for Automate Conversion of US/UC/UCC from MD to HTML

- index.html
I converted [Byte Ordering for Binary Data Formats #345](https://github.com/w3c/wot-usecases/issues/345) and [Polling Rate Limit #346](https://github.com/w3c/wot-usecases/issues/346) from MD to HTML, and added them in index.html.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/349.html" title="Last updated on Apr 2, 2025, 11:46 AM UTC (13b3ded)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/349/6f09b8f...13b3ded.html" title="Last updated on Apr 2, 2025, 11:46 AM UTC (13b3ded)">Diff</a>
> Add issue #345 and #346 in index.html

- index.html
There is a ReSpec Error. So I fixed typo in index.html following:
#STAKEHOLDER-System-Maintainter -> #STAKEHOLDER-System-Maintainer
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/368.html" title="Last updated on Jul 9, 2025, 2:26 AM UTC (34badd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/368/2ee113a...34badd3.html" title="Last updated on Jul 9, 2025, 2:26 AM UTC (34badd3)">Diff</a>
> Fixed typo ( Maintainter to Maintainer) in index.html

- index.html
- after discussion, kept the "Ideally..." sentence, even though it's a bit aspirational
- added sentence about "purpose is... to provide context"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/pull/374.html" title="Last updated on Jul 23, 2025, 11:26 AM UTC (490c499)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/374/77c9792...490c499.html" title="Last updated on Jul 23, 2025, 11:26 AM UTC (490c499)">Diff</a>
> Add Context to Use Case definition
